service: email-analyser
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:*
      Resource: '*'  

functions:
  email-analyser:
    handler: lambdas/endpoints/email-analyser.handler
    events:
      - http:
          path: analyse-email
          method: POST
          cors: true
